name: Invsee
version: 0.0.7
softdepend:
  - FakeInventories
depend:
  - FakeInventories
api: 1.0.0
author: Leon1917141
main: Invsee.Main
permissions:
  invsee.cmd:
    default: false
  endersee.cmd:
    default: false